### ISSUE TITLE
Videos put on static/videos isn't included in the build

### ISSUE THREAD

**Issue by musahi0128** [hugo-toha/guides#319]
Hi, I'm trying the shortcode for video

`{{< video src="/videos/zabbix-install.mp4" >}}`

But the video player isn't working.
Upon further checking, the video isn't included to the build.
Moving the video to static/files isn't working either, the video still not included to the build.
How can I fix this?
Thank you

**Comment by hossainemruz** [comment]
I suspect you haven't mounted your `static/videos` folder as module mount in your `hugo.yaml` file.
Please, check this example:
https://github.com/hugo-toha/hugo-toha.github.io/blob/8b173e09d7bb81ab842606cfb55d04613a8e05c6/hugo.yaml#L11

**Comment by musahi0128** [comment]
You are absolutely correct! I have no idea how to set it up beyond what you have documented.
This is the bits of relevant lines on `hugo.yaml`,
```yaml
...
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: static/videos # added
    target: static/videos # added
...
```
After the change, I can put the video in `static/videos` and it would appear under `public/videos` when the site is compiled.
Thank you very much!
